const loginView=document.getElementById('loginView'),dashboardView=document.getElementById('dashboardView'),loginForm=document.getElementById('loginForm'),loginNotice=document.getElementById('loginNotice'),dashboardNotice=document.getElementById('dashboardNotice'),logoutBtn=document.getElementById('logoutBtn');
const newAnimalBtn=document.getElementById('newAnimalBtn'),animalFormPanel=document.getElementById('animalFormPanel'),animalForm=document.getElementById('animalForm'),tableBody=document.getElementById('animalsTableBody'),emptyAnimals=document.getElementById('emptyAnimals'),fileInput=document.getElementById('animalPhoto'),photoPreview=document.getElementById('animalPhotoPreview');
const tabAnimals=document.getElementById('tabAnimals'),tabNews=document.getElementById('tabNews'),tabEvents=document.getElementById('tabEvents'),animalsSection=document.getElementById('animalsSection'),newsSection=document.getElementById('newsSection'),eventsSection=document.getElementById('eventsSection');
const newNewsBtn=document.getElementById('newNewsBtn'),newsFormPanel=document.getElementById('newsFormPanel'),newsForm=document.getElementById('newsForm'),newsTableBody=document.getElementById('newsTableBody'),emptyNews=document.getElementById('emptyNews'),newsImageInput=document.getElementById('newsImage');
const fields={id:document.getElementById('animalId'),name:document.getElementById('animalName'),species:document.getElementById('animalSpecies'),breed:document.getElementById('animalBreed'),age:document.getElementById('animalAge'),sex:document.getElementById('animalSex'),status:document.getElementById('animalStatus'),description:document.getElementById('animalDescription')};
const newsFields={id:document.getElementById('newsId'),title:document.getElementById('newsTitle'),excerpt:document.getElementById('newsExcerpt'),content:document.getElementById('newsContent'),published:document.getElementById('newsPublished'),date:document.getElementById('newsDate')};
const newEventBtn=document.getElementById('newEventBtn'),eventFormPanel=document.getElementById('eventFormPanel'),eventForm=document.getElementById('eventForm'),eventsTableBody=document.getElementById('eventsTableBody'),emptyEvents=document.getElementById('emptyEvents');
const tabFaq=document.getElementById('tabFaq'),faqSection=document.getElementById('faqSection'),newFaqBtn=document.getElementById('newFaqBtn'),faqFormPanel=document.getElementById('faqFormPanel'),faqForm=document.getElementById('faqForm'),faqTableBody=document.getElementById('faqTableBody'),emptyFaq=document.getElementById('emptyFaq');
const tabMembers=document.getElementById('tabMembers'),membersSection=document.getElementById('membersSection'),memberFormPanel=document.getElementById('memberFormPanel'),memberForm=document.getElementById('memberForm'),membersTableBody=document.getElementById('membersTableBody'),emptyMembers=document.getElementById('emptyMembers');
const memberFields={userId:document.getElementById('memberUserId'),email:document.getElementById('memberEmail'),role:document.getElementById('memberRole'),active:document.getElementById('memberActive'),mustChange:document.getElementById('memberMustChange')};
const faqFields={id:document.getElementById('faqId'),question:document.getElementById('faqQuestion'),answer:document.getElementById('faqAnswer'),published:document.getElementById('faqPublished'),order:document.getElementById('faqOrder')};
const eventFields={id:document.getElementById('eventId'),title:document.getElementById('eventTitle'),date:document.getElementById('eventDate'),published:document.getElementById('eventPublished'),start:document.getElementById('eventStart'),end:document.getElementById('eventEnd'),location:document.getElementById('eventLocation'),description:document.getElementById('eventDescription')};
let currentAnimals=[],currentNews=[],currentEvents=[],currentFaq=[],currentMembers=[],currentTeamRole='pending';
function showNotice(el,msg,error=false){el.textContent=msg;el.classList.remove('hidden');el.classList.toggle('error',error);}function hideNotice(el){el.classList.add('hidden');}
function statusLabel(s){return{available:'Disponible',reserved:'Réservé',adopted:'Adopté'}[s]||s}function statusClass(s){return s==='available'?'badge-available':s==='adopted'?'badge-adopted':'badge-reserved'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function resetForm(){animalForm.reset();fields.id.value='';document.getElementById('formTitle').textContent='Ajouter un animal';document.getElementById('fileName').textContent='Vous pouvez sélectionner plusieurs photos.';if(photoPreview)photoPreview.innerHTML='';animalFormPanel.classList.add('hidden');}
async function openForm(a=null){hideNotice(dashboardNotice);animalFormPanel.classList.remove('hidden');document.getElementById('formTitle').textContent=a?`Modifier ${a.name}`:'Ajouter un animal';fields.id.value=a?.id||'';fields.name.value=a?.name||'';fields.species.value=a?.species||'Chien';fields.breed.value=a?.breed||'';fields.age.value=a?.age||'';fields.sex.value=a?.sex||'Mâle';fields.status.value=a?.status||'available';fields.description.value=a?.description||'';fileInput.value='';if(photoPreview)photoPreview.innerHTML='';document.getElementById('fileName').textContent='Vous pouvez sélectionner plusieurs photos.';if(a?.id){const {data}=await supabaseClient.from('animal_photos').select('*').eq('animal_id',a.id).order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(Array.isArray(data)&&data.length){photoPreview.innerHTML=data.map(p=>`<div class="admin-photo-item"><img src="${esc(p.photo_url)}" alt="Photo de ${esc(a.name)}"><span>Photo ${p.sort_order+1}</span></div>`).join('');document.getElementById('fileName').textContent=`${data.length} photo(s) existante(s). Vous pouvez en ajouter d’autres.`;}else if(a.photo_url){photoPreview.innerHTML=`<div class="admin-photo-item"><img src="${esc(a.photo_url)}" alt="Photo de ${esc(a.name)}"><span>Photo principale actuelle</span></div>`;document.getElementById('fileName').textContent='Photo principale actuelle. Vous pouvez en ajouter d’autres.';}}animalFormPanel.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadAnimals(){const {data,error}=await supabaseClient.from('animals').select('*').order('created_at',{ascending:false});if(error){showNotice(dashboardNotice,`Impossible de charger les animaux : ${error.message}`,true);return;}currentAnimals=data||[];renderAnimals();}
function renderAnimals(){tableBody.innerHTML='';emptyAnimals.classList.toggle('hidden',currentAnimals.length!==0);currentAnimals.forEach(a=>{const tr=document.createElement('tr');const image=a.photo_url?`<img class="admin-thumb" src="${esc(a.photo_url)}" alt="Photo de ${esc(a.name)}">`:'<div class="admin-thumb"></div>';tr.innerHTML=`<td>${image}</td><td><strong>${esc(a.name)}</strong><br><small>${esc(a.species||'')}</small></td><td>${esc(a.breed||'—')} · ${esc(a.age||'âge non renseigné')} · ${esc(a.sex||'—')}</td><td><span class="badge ${statusClass(a.status)}">${statusLabel(a.status)}</span></td><td><div class="admin-actions"><button data-action="edit" data-id="${a.id}">Modifier</button><button class="danger" data-action="delete" data-id="${a.id}">Supprimer</button></div></td>`;tableBody.appendChild(tr);});}
async function uploadFile(file,bucket,folder,id){if(!file)return null;const safe=file.name.toLowerCase().replace(/[^a-z0-9.\-_]/g,'-');const path=`${folder}/${id}/${Date.now()}-${safe}`;const {error}=await supabaseClient.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabaseClient.storage.from(bucket).getPublicUrl(path).data.publicUrl;}
async function saveAnimal(e){e.preventDefault();hideNotice(dashboardNotice);const id=fields.id.value||crypto.randomUUID();const existing=currentAnimals.find(a=>a.id===id);let photoUrl=existing?.photo_url||null;try{const files=[...fileInput.files];let uploaded=[];if(files.length){uploaded=await Promise.all(files.map(f=>uploadFile(f,'animal-photos','animals',id)));if(!photoUrl)photoUrl=uploaded[0];}const payload={id,name:fields.name.value.trim(),species:fields.species.value,breed:fields.breed.value.trim()||null,age:fields.age.value.trim()||null,sex:fields.sex.value,status:fields.status.value,description:fields.description.value.trim()||null,photo_url:photoUrl};const {error}=await supabaseClient.from('animals').upsert(payload);if(error)throw error;if(uploaded.length){const startRes=await supabaseClient.from('animal_photos').select('sort_order').eq('animal_id',id).order('sort_order',{ascending:false}).limit(1);if(startRes.error)throw startRes.error;let next=Number(startRes.data?.[0]?.sort_order ?? -1)+1;const rows=uploaded.map((url,i)=>({animal_id:id,photo_url:url,sort_order:next+i}));const ins=await supabaseClient.from('animal_photos').insert(rows);if(ins.error)throw ins.error;}resetForm();showNotice(dashboardNotice,uploaded.length>1?`Animal enregistré avec ${uploaded.length} nouvelles photos.`: 'Animal enregistré avec succès.');await loadAnimals();}catch(err){showNotice(dashboardNotice,`Erreur lors de l’enregistrement : ${err.message}`,true)}}
async function deleteAnimal(id){const a=currentAnimals.find(x=>x.id===id);if(!a||!confirm(`Supprimer ${a.name} ?`))return;const {error}=await supabaseClient.from('animals').delete().eq('id',id);if(error){showNotice(dashboardNotice,`Impossible de supprimer l’animal : ${error.message}`,true);return;}showNotice(dashboardNotice,`${a.name} a été supprimé.`);await loadAnimals();}
function formatDate(v){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
function toLocalInput(v){if(!v)return'';const d=new Date(v);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function resetNewsForm(){newsForm.reset();newsFields.id.value='';newsFields.published.value='true';document.getElementById('newsFormTitle').textContent='Ajouter une actualité';document.getElementById('newsFileName').textContent='Aucune nouvelle image sélectionnée.';newsFormPanel.classList.add('hidden');}
function openNewsForm(n=null){hideNotice(dashboardNotice);newsFormPanel.classList.remove('hidden');document.getElementById('newsFormTitle').textContent=n?`Modifier ${n.title}`:'Ajouter une actualité';newsFields.id.value=n?.id||'';newsFields.title.value=n?.title||'';newsFields.excerpt.value=n?.excerpt||'';newsFields.content.value=n?.content||'';newsFields.published.value=String(n?.published??true);newsFields.date.value=toLocalInput(n?.published_at||new Date().toISOString());newsImageInput.value='';document.getElementById('newsFileName').textContent=n?.image_url?'Image actuelle conservée si aucune nouvelle image n’est choisie.':'Aucune image actuelle.';newsFormPanel.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadNews(){const {data,error}=await supabaseClient.from('news').select('*').order('published_at',{ascending:false}).order('created_at',{ascending:false});if(error){showNotice(dashboardNotice,`Impossible de charger les actualités : ${error.message}`,true);return;}currentNews=data||[];renderNews();}
function renderNews(){newsTableBody.innerHTML='';emptyNews.classList.toggle('hidden',currentNews.length!==0);currentNews.forEach(n=>{const tr=document.createElement('tr');const img=n.image_url?`<img class="news-admin-thumb" src="${esc(n.image_url)}" alt="${esc(n.title)}">`:'<div class="news-admin-thumb"></div>';tr.innerHTML=`<td>${img}</td><td><strong>${esc(n.title)}</strong><br><small>${esc(n.excerpt||'')}</small></td><td>${formatDate(n.published_at||n.created_at)}</td><td><span class="badge ${n.published?'badge-available':'badge-reserved'}">${n.published?'Publié':'Brouillon'}</span></td><td><div class="admin-actions"><button data-news-action="edit" data-id="${n.id}">Modifier</button><button class="danger" data-news-action="delete" data-id="${n.id}">Supprimer</button></div></td>`;newsTableBody.appendChild(tr);});}
async function saveNews(e){e.preventDefault();hideNotice(dashboardNotice);const id=newsFields.id.value||crypto.randomUUID();let imageUrl=currentNews.find(n=>n.id===id)?.image_url||null;try{if(newsImageInput.files[0])imageUrl=await uploadFile(newsImageInput.files[0],'news-images','news',id);const published=newsFields.published.value==='true';let publishedAt=newsFields.date.value?new Date(newsFields.date.value).toISOString():new Date().toISOString();const payload={id,title:newsFields.title.value.trim(),excerpt:newsFields.excerpt.value.trim()||null,content:newsFields.content.value.trim(),image_url:imageUrl,published,published_at:publishedAt};const {error}=await supabaseClient.from('news').upsert(payload);if(error)throw error;resetNewsForm();showNotice(dashboardNotice,'Actualité enregistrée avec succès.');await loadNews();}catch(err){showNotice(dashboardNotice,`Erreur lors de l’enregistrement : ${err.message}`,true)}}
async function deleteNews(id){const n=currentNews.find(x=>x.id===id);if(!n||!confirm(`Supprimer l’actualité « ${n.title} » ?`))return;const {error}=await supabaseClient.from('news').delete().eq('id',id);if(error){showNotice(dashboardNotice,`Impossible de supprimer l’actualité : ${error.message}`,true);return;}showNotice(dashboardNotice,'Actualité supprimée.');await loadNews();}

function resetEventForm(){eventForm.reset();eventFields.id.value='';eventFields.published.value='true';document.getElementById('eventFormTitle').textContent='Ajouter un événement';eventFormPanel.classList.add('hidden');}
function openEventForm(ev=null){hideNotice(dashboardNotice);eventFormPanel.classList.remove('hidden');document.getElementById('eventFormTitle').textContent=ev?`Modifier ${ev.title}`:'Ajouter un événement';eventFields.id.value=ev?.id||'';eventFields.title.value=ev?.title||'';eventFields.date.value=ev?.event_date||'';eventFields.published.value=String(ev?.published??true);eventFields.start.value=ev?.start_time?String(ev.start_time).slice(0,5):'';eventFields.end.value=ev?.end_time?String(ev.end_time).slice(0,5):'';eventFields.location.value=ev?.location||'';eventFields.description.value=ev?.description||'';eventFormPanel.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadEvents(){const {data,error}=await supabaseClient.from('events').select('*').order('event_date',{ascending:true}).order('start_time',{ascending:true});if(error){showNotice(dashboardNotice,`Impossible de charger les événements : ${error.message}`,true);return;}currentEvents=data||[];renderEvents();}
function eventDateTimeText(ev){const d=new Date(`${ev.event_date}T12:00:00`);const date=new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);const time=ev.start_time?String(ev.start_time).slice(0,5):'';return `${date}${time?` à ${time}`:''}`;}
function renderEvents(){eventsTableBody.innerHTML='';emptyEvents.classList.toggle('hidden',currentEvents.length!==0);currentEvents.forEach(ev=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${eventDateTimeText(ev)}</td><td><strong>${esc(ev.title)}</strong><br><small>${esc(ev.description||'')}</small></td><td>${esc(ev.location||'—')}</td><td><span class="badge ${ev.published?'badge-available':'badge-reserved'}">${ev.published?'Publié':'Brouillon'}</span></td><td><div class="admin-actions"><button data-event-action="edit" data-id="${ev.id}">Modifier</button><button class="danger" data-event-action="delete" data-id="${ev.id}">Supprimer</button></div></td>`;eventsTableBody.appendChild(tr);});}
async function saveEvent(e){e.preventDefault();hideNotice(dashboardNotice);const id=eventFields.id.value||crypto.randomUUID();const payload={id,title:eventFields.title.value.trim(),event_date:eventFields.date.value,start_time:eventFields.start.value||null,end_time:eventFields.end.value||null,location:eventFields.location.value.trim()||null,description:eventFields.description.value.trim()||null,published:eventFields.published.value==='true'};try{const {error}=await supabaseClient.from('events').upsert(payload);if(error)throw error;resetEventForm();showNotice(dashboardNotice,'Événement enregistré avec succès.');await loadEvents();}catch(err){showNotice(dashboardNotice,`Erreur lors de l’enregistrement : ${err.message}`,true)}}
async function deleteEvent(id){const ev=currentEvents.find(x=>x.id===id);if(!ev||!confirm(`Supprimer l’événement « ${ev.title} » ?`))return;const {error}=await supabaseClient.from('events').delete().eq('id',id);if(error){showNotice(dashboardNotice,`Impossible de supprimer l’événement : ${error.message}`,true);return;}showNotice(dashboardNotice,'Événement supprimé.');await loadEvents();}
function resetFaqForm(){faqForm.reset();faqFields.id.value='';faqFields.published.value='true';faqFields.order.value='0';document.getElementById('faqFormTitle').textContent='Ajouter une question';faqFormPanel.classList.add('hidden');}
function openFaqForm(f=null){hideNotice(dashboardNotice);faqFormPanel.classList.remove('hidden');document.getElementById('faqFormTitle').textContent=f?`Modifier la question`:'Ajouter une question';faqFields.id.value=f?.id||'';faqFields.question.value=f?.question||'';faqFields.answer.value=f?.answer||'';faqFields.published.value=String(f?.published??true);faqFields.order.value=String(f?.sort_order??0);faqFormPanel.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadFAQAdmin(){const {data,error}=await supabaseClient.from('faq_items').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(error){showNotice(dashboardNotice,`Impossible de charger la FAQ : ${error.message}`,true);return;}currentFaq=data||[];renderFAQAdmin();}
function renderFAQAdmin(){faqTableBody.innerHTML='';emptyFaq.classList.toggle('hidden',currentFaq.length!==0);currentFaq.forEach(f=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(f.sort_order??0)}</td><td><strong>${esc(f.question)}</strong></td><td><small>${esc(f.answer)}</small></td><td><span class="badge ${f.published?'badge-available':'badge-reserved'}">${f.published?'Publié':'Brouillon'}</span></td><td><div class="admin-actions"><button data-faq-action="edit" data-id="${f.id}">Modifier</button><button class="danger" data-faq-action="delete" data-id="${f.id}">Supprimer</button></div></td>`;faqTableBody.appendChild(tr);});}
async function saveFAQ(e){e.preventDefault();hideNotice(dashboardNotice);const id=faqFields.id.value||crypto.randomUUID();const payload={id,question:faqFields.question.value.trim(),answer:faqFields.answer.value.trim(),published:faqFields.published.value==='true',sort_order:Number(faqFields.order.value||0)};try{const {error}=await supabaseClient.from('faq_items').upsert(payload);if(error)throw error;resetFaqForm();showNotice(dashboardNotice,'Question FAQ enregistrée avec succès.');await loadFAQAdmin();}catch(err){showNotice(dashboardNotice,`Erreur lors de l’enregistrement : ${err.message}`,true)}}
async function deleteFAQ(id){const f=currentFaq.find(x=>x.id===id);if(!f||!confirm(`Supprimer la question « ${f.question} » ?`))return;const {error}=await supabaseClient.from('faq_items').delete().eq('id',id);if(error){showNotice(dashboardNotice,`Impossible de supprimer la question : ${error.message}`,true);return;}showNotice(dashboardNotice,'Question supprimée.');await loadFAQAdmin();}
function resetMemberForm(){memberForm?.reset();if(memberFields.userId)memberFields.userId.value='';if(memberFormPanel)memberFormPanel.classList.add('hidden');}
function openMemberForm(m){if(!m)return;hideNotice(dashboardNotice);memberFormPanel.classList.remove('hidden');document.getElementById('memberFormTitle').textContent=`Gérer ${m.email||'ce membre'}`;memberFields.userId.value=m.user_id;memberFields.email.value=m.email||'';memberFields.role.value=m.role||'pending';memberFields.active.value=String(m.active===true);memberFields.mustChange.value=String(m.must_change_password===true);memberFormPanel.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadMembers(){if(currentTeamRole!=='admin')return;const {data,error}=await supabaseClient.rpc('admin_list_team_members');if(error){showNotice(dashboardNotice,`Impossible de charger les membres : ${error.message}`,true);return;}currentMembers=data||[];renderMembers();}
function renderMembers(){membersTableBody.innerHTML='';emptyMembers.classList.toggle('hidden',currentMembers.length!==0);currentMembers.forEach(m=>{const tr=document.createElement('tr');const role=m.role==='benevole'?'Bénévole':'En attente';const access=m.active===true?'Activé':'Désactivé';const first=m.must_change_password===true?'À modifier':'Défini';tr.innerHTML=`<td><div class="member-email">${esc(m.email||'Compte sans e-mail')}</div><div class="member-meta">Créé le ${m.created_at?new Date(m.created_at).toLocaleDateString('fr-FR'):''}</div></td><td><span class="badge ${m.role==='benevole'?'badge-available':'badge-reserved'}">${role}</span></td><td><span class="badge ${m.active?'badge-available':'badge-reserved'}">${access}</span></td><td>${first}</td><td><div class="admin-actions"><button data-member-action="edit" data-id="${m.user_id}">Gérer</button></div></td>`;membersTableBody.appendChild(tr);});}
async function saveMember(e){e.preventDefault();if(currentTeamRole!=='admin'){showNotice(dashboardNotice,'Accès administrateur requis.',true);return;}hideNotice(dashboardNotice);const payload={p_user_id:memberFields.userId.value,p_role:memberFields.role.value,p_active:memberFields.active.value==='true',p_must_change_password:memberFields.mustChange.value==='true'};try{const {error}=await supabaseClient.rpc('admin_update_team_member',payload);if(error)throw error;resetMemberForm();showNotice(dashboardNotice,'Membre mis à jour avec succès.');await loadMembers();}catch(err){showNotice(dashboardNotice,`Erreur lors de la mise à jour : ${err.message}`,true);}}
function switchTab(tab){const isNews=tab==='news',isEvents=tab==='events',isFaq=tab==='faq',isMembers=tab==='members';animalsSection.classList.toggle('hidden',isNews||isEvents||isFaq||isMembers);newsSection.classList.toggle('hidden',!isNews);eventsSection.classList.toggle('hidden',!isEvents);faqSection.classList.toggle('hidden',!isFaq);membersSection?.classList.toggle('hidden',!isMembers);tabAnimals.classList.toggle('active',!isNews&&!isEvents&&!isFaq&&!isMembers);tabNews.classList.toggle('active',isNews);tabEvents.classList.toggle('active',isEvents);tabFaq?.classList.toggle('active',isFaq);tabMembers?.classList.toggle('active',isMembers);newAnimalBtn.classList.toggle('hidden',isNews||isEvents||isFaq||isMembers);if(isNews)loadNews();if(isEvents)loadEvents();if(isFaq)loadFAQAdmin();if(isMembers)loadMembers();}

async function updateView(session){
  if(!session){loginView.classList.remove('hidden');dashboardView.classList.add('hidden');logoutBtn.classList.add('hidden');return;}
  try{
    const {data:member,error}=await supabaseClient.from('team_members').select('role,active,must_change_password').eq('user_id',session.user.id).maybeSingle();
    if(error) throw error;
    if(member?.must_change_password===true){window.location.replace('connexion.html');return;}
    currentTeamRole=member?.role||'pending';tabMembers?.classList.toggle('hidden',currentTeamRole!=='admin');
    if(!member || member.active!==true || member.role==='pending'){
      await supabaseClient.auth.signOut();
      window.location.replace('connexion.html');
      return;
    }
    loginView.classList.add('hidden');dashboardView.classList.remove('hidden');logoutBtn.classList.remove('hidden');await loadAnimals();
  }catch(err){
    console.error('[SPAA admin auth]',err);
    await supabaseClient.auth.signOut();
    window.location.replace('connexion.html');
  }
}
loginForm.addEventListener('submit',async e=>{e.preventDefault();hideNotice(loginNotice);const {error}=await supabaseClient.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error)showNotice(loginNotice,error.message,true)});logoutBtn.addEventListener('click',()=>supabaseClient.auth.signOut());newAnimalBtn.addEventListener('click',()=>openForm());document.getElementById('cancelFormBtn').addEventListener('click',resetForm);animalForm.addEventListener('submit',saveAnimal);fileInput.addEventListener('change',()=>{const files=[...fileInput.files];document.getElementById('fileName').textContent=files.length?`${files.length} photo(s) sélectionnée(s).`:'Vous pouvez sélectionner plusieurs photos.';if(photoPreview){photoPreview.innerHTML=files.map(f=>{const url=URL.createObjectURL(f);return `<div class="admin-photo-item"><img src="${url}" alt="Aperçu ${esc(f.name)}"><span>${esc(f.name)}</span></div>`}).join('')}});tableBody.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const a=currentAnimals.find(x=>x.id===b.dataset.id);if(b.dataset.action==='edit')openForm(a);if(b.dataset.action==='delete')deleteAnimal(b.dataset.id);});
tabAnimals.addEventListener('click',()=>switchTab('animals'));tabNews.addEventListener('click',()=>switchTab('news'));newNewsBtn.addEventListener('click',()=>openNewsForm());document.getElementById('cancelNewsBtn').addEventListener('click',resetNewsForm);newsForm.addEventListener('submit',saveNews);newsImageInput.addEventListener('change',()=>document.getElementById('newsFileName').textContent=newsImageInput.files[0]?.name||'Aucune nouvelle image sélectionnée.');newsTableBody.addEventListener('click',e=>{const b=e.target.closest('button[data-news-action]');if(!b)return;const n=currentNews.find(x=>x.id===b.dataset.id);if(b.dataset.newsAction==='edit')openNewsForm(n);if(b.dataset.newsAction==='delete')deleteNews(b.dataset.id);});
if(tabMembers){tabMembers.addEventListener('click',()=>switchTab('members'));document.getElementById('cancelMemberBtn').addEventListener('click',resetMemberForm);memberForm.addEventListener('submit',saveMember);membersTableBody.addEventListener('click',e=>{const b=e.target.closest('button[data-member-action]');if(!b)return;if(b.dataset.memberAction==='edit')openMemberForm(currentMembers.find(x=>x.user_id===b.dataset.id));});}
supabaseClient.auth.onAuthStateChange((_event,session)=>updateView(session));
(async()=>{const {data:{session}}=await supabaseClient.auth.getSession();await updateView(session)})();

if(tabEvents){tabEvents.addEventListener('click',()=>switchTab('events'));newEventBtn.addEventListener('click',()=>openEventForm());document.getElementById('cancelEventBtn').addEventListener('click',resetEventForm);eventForm.addEventListener('submit',saveEvent);eventsTableBody.addEventListener('click',e=>{const b=e.target.closest('button[data-event-action]');if(!b)return;if(b.dataset.eventAction==='edit')openEventForm(currentEvents.find(x=>x.id===b.dataset.id));if(b.dataset.eventAction==='delete')deleteEvent(b.dataset.id);});}

if(tabFaq){tabFaq.addEventListener('click',()=>switchTab('faq'));newFaqBtn.addEventListener('click',()=>openFaqForm());document.getElementById('cancelFaqBtn').addEventListener('click',resetFaqForm);faqForm.addEventListener('submit',saveFAQ);faqTableBody.addEventListener('click',e=>{const b=e.target.closest('button[data-faq-action]');if(!b)return;if(b.dataset.faqAction==='edit')openFaqForm(currentFaq.find(x=>x.id===b.dataset.id));if(b.dataset.faqAction==='delete')deleteFAQ(b.dataset.id);});}
